const D={
"founder-dependency":["Example: purchase approval","A ₹35,000 routine purchase waits two days because only the founder can approve it. The team maps the decision: approved vendors, budget availability, stock threshold and delivery urgency. A manager receives authority up to ₹50,000 when all four conditions are met; price variance above 8% or a new vendor triggers escalation. The founder reviews exceptions weekly. This converts one repeated approval into a controlled decision system—without giving unlimited spending authority.",["Which three questions reach the founder most often?","What information does the founder use that the team cannot currently see?","What is the smallest safe boundary that can be tested for two weeks?"]],
"people-teams":["Example: collections ownership","“Improve collections” is replaced with an observable outcome: every invoice above 30 days must have a named owner, customer-confirmed next action and expected receipt date by Thursday. Disputes above ₹1 lakh escalate to the finance lead. The weekly review separates missing data, customer disputes and follow-up discipline. This makes it possible to coach the actual constraint instead of labelling the employee unmotivated.",["Can two people independently explain what good performance looks like?","Does the role have authority over the choices required to deliver its outcome?","Is the review based on evidence available before the meeting?"]],
"process-operations":["Example: sales-to-delivery handoff","Delivery repeatedly calls sales for scope details after a deal closes. The team observes ten handoffs and finds four required fields are often missing. They create a one-page acceptance checklist, name the delivery coordinator as receiver and start the turnaround clock only after acceptance. First-pass acceptance and rework are tracked for four weeks. The SOP is updated from real exceptions, not from assumptions in a conference room.",["Where does work wait between two roles?","Which missing input causes the most rework or customer delay?","Who owns the performance of the whole process, not only one task?"]],
"sales-growth":["Example: removing false pipeline","A ₹40 lakh pipeline looks healthy, but six large opportunities have no customer interaction scheduled. The team applies qualification evidence and moves four deals to nurture. The forecast becomes smaller but more reliable. The weekly review then focuses on the remaining deals’ decision process, obstacle and dated customer action. Management can now distinguish pipeline creation, pipeline movement and conversion rather than discussing one inflated total.",["What evidence is required to enter each stage?","How many active opportunities have no dated customer-facing action?","Which stage has the longest age and lowest conversion?"]],
"finance-decisions":["Example: collections decision board","Instead of reviewing a 20-page receivables report, the leadership team uses four views: amount overdue by age, top exposures, named next action and expected receipt date. A threshold identifies disputes needing founder or legal attention. The dashboard does not replace detailed records; it turns them into a weekly decision surface. Forecast accuracy and overdue reduction reveal whether the rhythm is working.",["Which five financial decisions repeat every week or month?","Can everyone reproduce each measure from the same source and definition?","What threshold requires action rather than explanation?"]],
"delegation-boundaries":["Example: customer service recovery","A service manager can approve recovery up to ₹10,000 when the failure is documented and the customer is within an agreed segment. Safety issues, legal threats and repeat failures escalate immediately. Every recovery is reviewed weekly by type and root cause. The manager gains real authority, the founder retains control of high-consequence cases and the business learns which process failures create repeated cost.",["What outcome is delegated but what decision is still retained?","Which red-line trigger can be observed without interpretation?","How will mistakes become learning rather than automatic withdrawal of authority?"]],
"execution-rhythm":["Example: launching a distributor review","“Improve distributor performance” becomes a 30-day learning priority. One owner must segment distributors, test a review format with five partners and present findings on a fixed date. The measure is not immediate revenue; it is completion of the test, quality of evidence and the next decision. Once the method is understood, the team can set a harder performance goal with relevant feedback.",["How many improvement priorities does each owner currently carry?","Does every priority have a next observable deliverable?","Is the next review already scheduled, and what evidence will be examined?"]]
};const depth=D[document.body.dataset.article];if(depth){const hs=[...document.querySelectorAll(".prose>h2")],practical=hs.find(h=>h.textContent.includes("30-day"));practical.insertAdjacentHTML("beforebegin",`<section class="worked-example"><h2>${depth[0]}</h2><p>${depth[1]}</p></section><section class="diagnostic"><h2>Diagnostic questions before you act</h2><ol>${depth[2].map(q=>`<li>${q}</li>`).join("")}</ol></section>`);document.querySelector(".meta").textContent="Shikha Solutions Founder Insights · 6–8 minute read";}

